INSERT INTO `tables` VALUES (1, 'countries');
INSERT INTO `tables` VALUES (2, 'cities');
INSERT INTO `fields` VALUES (1, 1, 'id', 'integer');
INSERT INTO `fields` VALUES (2, 1, 'name', 'string');
INSERT INTO `fields` VALUES (3, 2, 'id', 'integer');
INSERT INTO `fields` VALUES (4, 2, 'country_id', 'integer');
INSERT INTO `fields` VALUES (5, 2, 'name', 'string');
INSERT INTO `relations` VALUES (4, 1, 'many-to-one');
INSERT INTO `data` VALUES (2, 'Russia', 1);
INSERT INTO `data` VALUES (2, 'Germany', 2);
INSERT INTO `data` VALUES (2, 'Japan', 3);
INSERT INTO `data` VALUES (1, 1, 1);
INSERT INTO `data` VALUES (1, 2, 2);
INSERT INTO `data` VALUES (1, 3, 3);
INSERT INTO `data` VALUES (5, 'Moscow', 4);
INSERT INTO `data` VALUES (5, 'Berlin', 5);
INSERT INTO `data` VALUES (5, 'Tokyo', 6);
INSERT INTO `data` VALUES (5, 'Saint Petersburg', 7);
INSERT INTO `data` VALUES (3, 1, 4);
INSERT INTO `data` VALUES (3, 2, 5);
INSERT INTO `data` VALUES (3, 3, 6);
INSERT INTO `data` VALUES (3, 4, 7);
INSERT INTO `data` VALUES (4, 1, 4);
INSERT INTO `data` VALUES (4, 2, 5);
INSERT INTO `data` VALUES (4, 3, 6);
INSERT INTO `data` VALUES (4, 1, 7);
